### PR TITLE
Fix electrical on shutdown checklist

### LINKED ISSUE #1: Electrical on the Shutdown checklist is not correct
**Airplane**: Zibo Mod (3.51.16)
**SOP**: B737_ZiboDefault
**Checklist**: Shutdown and Shutdown (Transit)
**Checklist item**: Electrical

**Describe the bug**
If the APU is on the bus instead of the GPU, the Electrical item fails.

**Expected behavior**
The Electrical item should succeed when either the APU or the GPU is on the bus.

### PR DESCRIPTION
**Pull request by patrickl92**
Closes #1

### CODE REVIEW

**Comment by elvinbarrow** [comment]
Hi Patrick,  saw a video from FD2SIM and it seemed like he was using v1.5 of your plugin, is it possible to show me where I can get it from please. Also it would seem like it is also x-plane 12 compatible, is that correct?

**Comment by patrickl92** [comment]
> Hi Patrick,  saw a video from FD2SIM and it seemed like he was using v1.5 of your plugin, is it possible to show me where I can get it from please. Also it would seem like it is also x-plane 12 compatible, is that correct?

Hi, FD2S uses the latest version. You can get the base plugin from here: https://github.com/patrickl92/AudioChecklist

Then you need to install the Zibo SOP from here: https://github.com/patrickl92/AudioChecklistSOPs

The plugin also works with X-Plane 12. Just make sure you install the FlyWithLua version for X-Plane 12.

Let me know if you encounter any problems during the installation.

**Comment by elvinbarrow** [comment]
Thanks Patrick, much appreciated :)

**Comment by elvinbarrow** [comment]
Hi Patrick,

I just installed and have noticed that it is having issues with detecting that I have performed the WHEEL WELL FIRE WARNING test, not sure if this is an issue as I can skip.

Cheers

**Comment by patrickl92** [comment]
I have seen this issue on the streams of FD2S as well, but I don't know what's causing this, becase it works for me. Had you started the audio checklist SOP prior to executing the wheel well fire warning test?

Maybe it has something to do with the Zibo version. There were other issues initially on X-Plane 12, which were fixed by updates of the Zibo mod.

**Pull request merged**
